#!/usr/bin/env python3

from letmecreate.core.common import MIKROBUS_1
from letmecreate.core.common import MIKROBUS_2
from letmecreate.core import led
from letmecreate.core import i2c
from letmecreate.click import motion
from letmecreate.click import thermo3
from time import sleep

KEY = "26ZRSL4VV3NGS7UB"



def send_temp(arg):
    # Only flash LED's when motion starts getting detected.
    if arg != 1:
        return

    for i in range(10):
        led.switch_on(led.ALL_LEDS)
        sleep(0.1)
        led.switch_off(led.ALL_LEDS)
        sleep(0.1)

    temp  = str(thermo3.get_temperature())
    rcall = []
    rcall.append("wget")
    rcall.append("https://api.thingspeak.com/update?api_key={}&field1={}".format(KEY, temp))
    subprocess.run(rcall)


led.init()
i2c.init()

i2c.select_bus(MIKROBUS_1)

thermo3.enable(MIKROBUS_1)
motion.enable(MIKROBUS_2)

motion.attach_callback(MIKROBUS_2, send_temp)

print("LED's will flash when Motion Click detects a movement.\n")
print("Press Ctrl+C to quit.\n")


while True:
    pass
